#!/bin/sh

. /usr/lib/vdr/config-loader.sh

VDR_ENV="LANG=$VDR_LANG LC_ALL=$VDR_LANG"

VDRCMD="$VDR_ENV /usr/bin/vdr $*"

VDR_ERR=`mktemp -p /tmp vdr-err.XXXXXX`

while (true) do
    eval $VDRCMD >/dev/null 2>"$VDR_ERR"

    case $? in
        0)
            exit
        ;;
        2)
            ERROR=`cat "$VDR_ERR"`
            logger -t runvdr "stopping after fatal fail ($ERROR)"
            exit
        ;;
        3)
            ERROR=`cat "$VDR_ERR"`
            logger -t runvdr "stopping after dvb device fail ($ERROR)"
	    [ -x /etc/vdr/dvbdevicefailure ] && /etc/vdr/dvbdevicefailure
            exit
        ;;
    esac

    logger -t runvdr "restarting VDR"
done
